# Generated by Django 3.1.7 on 2021-10-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='author_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='conversation_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='twitter_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
