# Generated by Django 3.1.7 on 2021-10-22 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delab', '0002_auto_20211020_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.BigIntegerField()),
                ('name', models.TextField()),
                ('screen_name', models.TextField()),
                ('location', models.TextField()),
                ('followers_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='tw_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delab.tweetauthor'),
        ),
    ]
