# Generated by Django 3.1.7 on 2021-10-25 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delab', '0004_auto_20211025_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tw_author',
        ),
        migrations.RemoveField(
            model_name='tweetauthor',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delab.tweetauthor'),
        ),
        migrations.AlterField(
            model_name='tweetauthor',
            name='twitter_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
