# Generated by Django 3.1.7 on 2021-10-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delab', '0005_auto_20211025_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tw_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delab.tweetauthor'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='author_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
