# Generated by Django 3.1.7 on 2021-10-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delab', '0006_auto_20211025_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetauthor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweetauthor',
            name='twitter_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
