# Generated by Django 3.1.7 on 2021-10-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delab', '0007_auto_20211025_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplerequest',
            name='fast_mode',
            field=models.BooleanField(default=False, help_text='this is for debugging and getting quick results. It will not download the user data'),
        ),
    ]
